[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8501"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"